import 'package:equatable/equatable.dart';

class MenuItem extends Equatable {
  final int id;
  final int restaurantId;
  final String name;
  final String category;
  final String description;
  final double price;

  MenuItem(
      {required this.id,
      required this.restaurantId,
      required this.name,
      required this.category,
      required this.description,
      required this.price});

  @override
  List<Object?> get props => [id, restaurantId, name, category, description, price];

  static List<MenuItem> menuItems = [
    MenuItem(
        id: 1,
        restaurantId: 1,
        name: 'Margharita',
        category: 'Pizza',
        description: 'Pizza Margherita is a typical Neapolitan pizza, made with San Marzano tomatoes, mozzarella cheese, fresh basil, salt, and extra-virgin olive oil.',
        price: 5.99),
    MenuItem(
        id: 1,
        restaurantId: 1,
        name: '4 Formaggi',
        category: 'Pizza',
        description: 'Pizza quattro formaggi Italian: is a variety of pizza in Italian cuisine that is topped with a combination of four kinds of cheese, usually melted together, with or without tomato sauce.',
        price: 6.99),
    MenuItem(
        id: 1,
        restaurantId: 2,
        name: 'Margarita',
        category: 'Pizza',
        description: 'Pizza Margherita is a typical Neapolitan pizza, made with San Marzano tomatoes, mozzarella cheese, fresh basil, salt, and extra-virgin olive oil.',
        price: 5.99),
    MenuItem(
        id: 5,
        restaurantId: 1,
        name: 'Coca Cola',
        category: 'Drink',
        description: 'Bottle of Coca Cola',
        price: 1.99),
    MenuItem(
        id: 1,
        restaurantId: 3,
        name: 'Chicago Pizza',
        category: 'Pizza',
        description: 'Chicago-style pizza is pizza prepared according to several different styles developed in Chicago',
        price: 6.50),
    MenuItem(
        id: 1,
        restaurantId: 3,
        name: 'Margarita',
        category: 'Pizza',
        description: 'Pizza Margherita is a typical Neapolitan pizza, made with San Marzano tomatoes, mozzarella cheese, fresh basil, salt, and extra-virgin olive oil.',
        price: 5.99),
    MenuItem(
        id: 1,
        restaurantId: 4,
        name: 'Chicago Pizza',
        category: 'Pizza',
        description: 'Chicago-style pizza is pizza prepared according to several different styles developed in Chicago',
        price: 7.99),
    MenuItem(
        id: 2,
        restaurantId: 4,
        name: 'The Crispy Bun',
        category: 'Burger',
        description: 'Beef Burgers',
        price: 3.55),
    MenuItem(
        id: 2,
        restaurantId: 3,
        name: 'Turkey Burgers',
        category: 'Burger',
        description: 'Turkey Burgers',
        price: 3.55),
    MenuItem(
        id: 2,
        restaurantId: 5,
        name: 'Turkey Burgers',
        category: 'Burger',
        description: 'Turkey Burgers',
        price: 3.55),
    MenuItem(
        id: 3,
        restaurantId: 4,
        name: 'Classic Greek Salad',
        category: 'Salad',
        description: 'olive oil, red wine vinegar, lemon juice, Dijon mustard, minced garlic cloves',
        price: 4.55),
    MenuItem(
        id: 3,
        restaurantId: 1,
        name: 'Classic Greek Salad',
        category: 'Salad',
        description: 'olive oil, red wine vinegar, lemon juice, Dijon mustard, minced garlic cloves',
        price: 6.20),
    MenuItem(
        id: 3,
        restaurantId: 2,
        name: 'Pad Thai Salad with Coconut Lime Dressing',
        category: 'Salad',
        description: '1 clove raw garlic, 1 teaspoon fresh grated ginger, 1 tablespoon shoyu, 4 tablespoons mirin, 1 tablespoon organic maple syrup,2 tablespoon tahini or macadamia nut butter,2 tablespoons water to mix',
        price: 8.50),
    MenuItem(
        id: 3,
        restaurantId: 6,
        name: 'Green Goddess Chicken Salad',
        category: 'Salad',
        description: 'herbs - chives and parsley',
        price: 5.55),
    MenuItem(
        id: 3,
        restaurantId: 4,
        name: 'Fruity Pasta Salad',
        category: 'Salad',
        description: 'strawberries, pineapple, honeydew, watermelon, grapes, and kiwifruit',
        price: 6.50),
    MenuItem(
        id: 3,
        restaurantId: 5,
        name: 'Fruity Pasta Salad',
        category: 'Salad',
        description: 'strawberries, pineapple, honeydew, watermelon, grapes, and kiwifruit',
        price: 6.50),
    MenuItem(
        id: 5,
        restaurantId: 1,
        name: 'Water',
        category: 'Drink',
        description: 'Bottle of water',
        price: 1.99),
    MenuItem(
        id: 5,
        restaurantId: 2,
        name: 'Water',
        category: 'Drink',
        description: 'Bottle of water',
        price: 1.99),
    MenuItem(
        id: 5,
        restaurantId: 3,
        name: 'Water',
        category: 'Drink',
        description: 'Bottle of water',
        price: 1.99),
    MenuItem(
        id: 5,
        restaurantId: 4,
        name: 'Water',
        category: 'Drink',
        description: 'Bottle of water',
        price: 1.99),
    MenuItem(
        id: 5,
        restaurantId: 5,
        name: 'Water',
        category: 'Drink',
        description: 'Bottle of water',
        price: 1.99),
    MenuItem(
        id: 5,
        restaurantId: 6,
        name: 'Water',
        category: 'Drink',
        description: 'Bottle of water',
        price: 1.99),
    MenuItem(
        id: 5,
        restaurantId: 2,
        name: 'Coca Cola',
        category: 'Drink',
        description: 'Bottle of Coca Cola',
        price: 1.99),
    MenuItem(
        id: 5,
        restaurantId: 3,
        name: 'Coca Cola',
        category: 'Drink',
        description: 'Bottle of Coca Cola',
        price: 1.99),
    MenuItem(
        id: 5,
        restaurantId: 4,
        name: 'Coca Cola',
        category: 'Drink',
        description: 'Bottle of Coca Cola',
        price: 1.99),
    MenuItem(
        id: 5,
        restaurantId: 5,
        name: 'Coca Cola',
        category: 'Drink',
        description: 'Bottle of Coca Cola',
        price: 1.99),
    MenuItem(
        id: 5,
        restaurantId: 6,
        name: 'Coca Cola',
        category: 'Drink',
        description: 'Bottle of Coca Cola',
        price: 1.99),
    MenuItem(
        id: 5,
        restaurantId: 1,
        name: 'Fanta',
        category: 'Drink',
        description: 'Bottle of Fanta',
        price: 1.99),
    MenuItem(
        id: 5,
        restaurantId: 2,
        name: 'Fanta',
        category: 'Drink',
        description: 'Bottle of Fanta',
        price: 1.99),
    MenuItem(
        id: 5,
        restaurantId: 3,
        name: 'Fanta',
        category: 'Drink',
        description: 'Bottle of Fanta',
        price: 1.99),
    MenuItem(
        id: 5,
        restaurantId: 4,
        name: 'Fanta',
        category: 'Drink',
        description: 'Bottle of Fanta',
        price: 1.99),
    MenuItem(
        id: 5,
        restaurantId: 5,
        name: 'Fanta',
        category: 'Drink',
        description: 'Bottle of Fanta',
        price: 1.99),
    MenuItem(
        id: 5,
        restaurantId: 6,
        name: 'Fanta',
        category: 'Drink',
        description: 'Bottle of Fanta',
        price: 1.99),
    MenuItem(
        id: 4,
        restaurantId: 2,
        name: 'Angel Cake',
        category: 'Dessert',
        description: 'Angel food cake, or angel cake, is a type of sponge cake made with egg whites, flour, and sugar',
        price: 1.99),
    MenuItem(
        id: 4,
        restaurantId: 2,
        name: 'Banana Cake',
        category: 'Dessert',
        description: 'Banana Cake',
        price: 3.99),
    MenuItem(
        id: 4,
        restaurantId: 2,
        name: 'Baumkuchen',
        category: 'Dessert',
        description: 'Baumkuchen is a kind of spit cake from German cuisine',
        price: 3.99),
    MenuItem(
        id: 4,
        restaurantId: 5,
        name: 'Angel Cake',
        category: 'Dessert',
        description: 'Angel food cake, or angel cake, is a type of sponge cake made with egg whites, flour, and sugar',
        price: 3.99),
    MenuItem(
        id: 4,
        restaurantId: 5,
        name: 'Banana Cake',
        category: 'Dessert',
        description: 'Banana Cake',
        price: 3.99),
    MenuItem(
        id: 4,
        restaurantId: 5,
        name: 'Brownie',
        category: 'Dessert',
        description: 'fudgy, chewy, and cakey ',
        price: 3.99),
    MenuItem(
        id: 4,
        restaurantId: 5,
        name: 'Carrot Cake',
        category: 'Dessert',
        description: 'Loaf, sheet cake, layer cake, cupcake',
        price: 3.99),
    MenuItem(
        id: 4,
        restaurantId: 5,
        name: 'Cupcake',
        category: 'Dessert',
        description: 'Coconut Cupcakes, Margarita Cupcakes, Dark Chocolate Cupcakes',
        price: 3.99),
  ];
}
